# Generated by Django 5.0.1 on 2024-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_medicine_visit_eating_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='medicine_name',
            field=models.ManyToManyField(related_name='visits', to='shop.medicine'),
        ),
    ]
