# Generated by Django 5.0.1 on 2024-04-21 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_visit_medicine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
