# Generated by Django 5.0.1 on 2024-04-21 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_name_medicine_medicine_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='eating_status',
        ),
    ]
