# Generated by Django 5.0.1 on 2024-04-24 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_visit_eating_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.visit')),
            ],
        ),
    ]
