# Generated by Django 5.0.1 on 2024-05-23 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_patientvisit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='medicine_name',
            new_name='medicines',
        ),
    ]
