# Generated by Django 5.0.1 on 2024-05-23 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_medicine_name_visit_medicines'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='medicines',
            new_name='medicine_names',
        ),
    ]
