# Generated by Django 5.0.1 on 2024-05-23 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_medicines_visit_medicine_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='medicine_names',
            new_name='medicine_name',
        ),
    ]
