# Generated by Django 5.0.1 on 2024-05-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_medicine_names_visit_medicine_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='medicine_name',
            new_name='medicines',
        ),
    ]
