# Generated by Django 5.0.1 on 2024-05-28 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_rename_medicine_name_visit_medicines'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisitMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.visit')),
            ],
        ),
        migrations.AlterField(
            model_name='visit',
            name='medicines',
            field=models.ManyToManyField(related_name='visits', through='shop.PatientVisitMedicine', to='shop.medicine'),
        ),
    ]
