# Generated by Django 5.0.1 on 2024-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_patientvisitmedicine_alter_visit_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='medicines',
            field=models.ManyToManyField(related_name='visit_medicines', through='shop.PatientVisitMedicine', to='shop.medicine'),
        ),
    ]
