# Generated by Django 5.0.1 on 2024-05-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_visit_medicines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='medicines',
            field=models.ManyToManyField(related_name='visits', to='shop.medicine'),
        ),
        migrations.DeleteModel(
            name='PatientVisitMedicine',
        ),
    ]
