# Generated by Django 5.0.1 on 2024-05-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_visit_medicines_delete_patientvisitmedicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='medicines',
        ),
        migrations.AddField(
            model_name='visit',
            name='old_medicines',
            field=models.ManyToManyField(related_name='old_visits', to='shop.medicine'),
        ),
    ]
