# Generated by Django 5.0.1 on 2024-05-28 05:37

from django.db import migrations

def migrate_old_medicines_to_medicines(apps, schema_editor):
    Visit = apps.get_model('shop', 'Visit')
    Medicine = apps.get_model('shop', 'Medicine')
    
    # Migrate data from old_medicines to medicines
    for visit in Visit.objects.all():
        for medicine in visit.old_medicines.all():
            visit.medicines.add(medicine)

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_visit_medicines_visit_old_medicines'),  # Adjust based on your last migration
    ]

    operations = [
        migrations.RunPython(migrate_old_medicines_to_medicines),
    ]

